### ISSUE TITLE
new docker compose features (profiles, extends) can replace your app-enable env vars

### ISSUE THREAD

**Issue by beyondmeat** [Makeshift/Media-Compose-Stack#15]
docker-compose.yml
```
  sabnzbd:
    extends:
      file: ./apps/docker-compose.sabnzbd.yml
      service: sabnzbd
    profiles:
      - sabnzbd
     networks: #override
      - wg-net
```

.env
```
COMPOSE_PROFILES=sabnzbd,radarr,radarr4k
```

compose v2
